### ISSUE TITLE
How to ignore TS type check in node_modules during build?

### ISSUE THREAD

**Issue by HUANGXUANKUN** [umijs/dumi#1003]
### Question
It works well in dev mode, but when comes to running `dumi build`, it throws TS errors on type checking for files in node_modules.

How do we setup tsconfig in father build to aviod such tscheck in build process.

### Error message
```sh
xxxxx/node_modules/xxxxx/some_file.ts(315,57): error TS2345: 
Argument of type '{ <T>(list: readonly T[]): T[]; (list: string): string; }' is not assignable to parameter of type '(a:payload) => string'.
Transform to esm for src/index.js
Transform to esm for src/form/constant.js
Transform to esm for src/form/index.js
TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: TypeScript: Compilation failed
    at Output.mightFinish (xxxx/node_modules/gulp-typescript/release/output.js:130:43)
    at /xxxx/node_modules/gulp-typescript/release/output.js:65:22
Emitted 'error' event on Duplexify instance at:
    at Duplexify._destroy (xxxxx/node_modules/duplexify/index.js:191:15)
    at /xxxxx/node_modules/duplexify/index.js:182:10
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
error Command failed with exit code 1.
```

### Setup
I have setup `tsconfig.json` with skipLibCheck=true, as follows. Does Father build uses such setup?

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "esModuleInterop": true,
    "types": ["jest"],
    "strict": true,
    "skipLibCheck": true,
    "declaration": true,
    "resolveJsonModule": true, // TODO: check this out
    "strictFunctionTypes": false
  },
  "include": ["./src"],
  "exclude": ["node_modules"]
}
```

**Comment by hnxyhcz** [comment]
问下解决了吗？我的也有这个问题，build的时候ts会检查node_modules里的文件

**Comment by huangkairan** [comment]
@sorrycc

**Comment by PeachScript** [comment]
These errors are thrown by gulp-typescript of father v2, which is no longer maintained, please upgrade to father v4: https://github.com/umijs/father/blob/master/docs/guide/upgrading.md

这些错误是 father v2 使用的 gulp-typescript 抛出的，它已不再维护，请升级到 father v4：https://github.com/umijs/father/blob/master/docs/guide/upgrading.md
