### ISSUE TITLE
bug: config.nodeModulesTransform invalid

### ISSUE THREAD

**Issue by hotoo** [umijs/dumi#1059]
### Versions

- dumi: 1.1.40
- node: 16.14.0
- npm: 8.3.1
- OS: macOS Monterey M1 mbp
- Browser: Chrome 99.0.4844.51（正式版本） (arm64)

### Steps to reproduce

I'm write pinyin@3.x https://github.com/hotoo/pinyin/tree/v3.x in typescript, 
it use "nodejieba" and "@node-rs/jieba" for segment, dumi can't compile this.

I'm trying .umirc.js:

```js
  nodeModulesTransform: {
    type: 'none',
  },
```

or:

```
  nodeModulesTransform: {
    type: 'all',
    exclude: ['nodejieba', '@node-rs/jieba'],
  },

```

### What is Expected?

I expect dumi don't compile "nodejieba" and "@node-rs/jieba", pinyin didn't use it in web browser.

### What is actually happening?

but dumi still compile the node_modules and throw error:

```
✖ MFSU
  Compiled with some errors in 7.41s

✔ Webpack
  


  App running at:
  - Local:   http://localhost:8000 (copied to clipboard)
  - Network: http://192.168.50.65:8000
 ERROR  Failed to compile with 2 errors                                                                                                           08:34:49

 error  in ./node_modules/_@mapbox_node-pre-gyp@1.0.8@@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>
| <html>
| <head>

 error  in ./node_modules/_@node-rs_jieba-darwin-arm64@1.6.0@@node-rs/jieba-darwin-arm64/jieba.darwin-arm64.node

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)


✖ MFSU
  

✔ Webpack
  

ERROR in ./node_modules/_@mapbox_node-pre-gyp@1.0.8@@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>
| <html>
| <head>
 @ ./node_modules/_@mapbox_node-pre-gyp@1.0.8@@mapbox/node-pre-gyp/lib/ sync ^\.\/.*$ ./util/nw-pre-gyp/index.html
 @ ./node_modules/_@mapbox_node-pre-gyp@1.0.8@@mapbox/node-pre-gyp/lib/node-pre-gyp.js 86:13-36 291:36-53
 @ ./node_modules/_nodejieba@2.5.2@nodejieba/index.js 1:13-44
 @ ./src/.umi/.cache/.mfsu/mf-va_nodejieba.js 1:0-26 2:15-16 3:0-26 3:0-26
 @ container entry ./nodejieba[0]

ERROR in ./node_modules/_@node-rs_jieba-darwin-arm64@1.6.0@@node-rs/jieba-darwin-arm64/jieba.darwin-arm64.node 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/_@node-rs_jieba@1.6.0@@node-rs/jieba/index.js 117:28-66
 @ ./src/.umi/.cache/.mfsu/mf-va_@node-rs_jieba.js 1:0-31 2:15-16 3:0-31 3:0-31
 @ container entry ./@node-rs/jieba[0]

webpack compiled with 2 errors
null
Error: build failed
    at /Users/modu/workbench/github.com/hotoo/pinyin/node_modules/_@umijs_bundler-webpack@3.5.21@@umijs/bundler-webpack/lib/index.js:172:29
    at /Users/modu/workbench/github.com/hotoo/pinyin/node_modules/_@umijs_deps@3.5.21@@umijs/deps/compiled/webpack/5/bundle5.js:114591:14
    at processQueueWorker (/Users/modu/workbench/github.com/hotoo/pinyin/node_modules/_@umijs_deps@3.5.21@@umijs/deps/compiled/webpack/5/bundle5.js:114529:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
^Cnpm notice 
npm notice New minor version of npm available! 8.3.1 -> 8.5.5
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.5.5
npm notice Run npm install -g npm@8.5.5 to update!
npm notice 
```

**Comment by hotoo** [comment]
rm -rf src/.umi resolved.
