### ISSUE TITLE
dumi 工程下使用 umi test 报错

### ISSUE THREAD

**Issue by javaxiu** [umijs/dumi#1082]
### Question

基于 dumi 搭建了一个组件库，配置 umi test 时遇到这样的错误，错误提示里的 logo/mode 等字段是 dumi 的 .umirc 里配置的，这些应该是 dumi 对 .umirc 的扩展配置，请问如何绕过这样的错误呢？
```cli
npm run test:watch

> test:watch
> umi test --watch

Invalid config keys: logo, mode, resolve, navs, menus
Error: Invalid config keys: logo, mode, resolve, navs, menus
    at Config.getConfig (/Users/jiawen/workspace/wecalendar-web-component/node_modules/@umijs/core/lib/Config/Config.js:183:13)
    at /Users/jiawen/workspace/wecalendar-web-component/node_modules/@umijs/core/lib/Service/Service.js:293:44
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/jiawen/workspace/wecalendar-web-component/node_modules/@umijs/core/lib/Service/Service.js:110:103)
    at _next (/Users/jiawen/workspace/wecalendar-web-component/node_modules/@umijs/core/lib/Service/Service.js:112:194)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by PeachScript** [comment]
执行 `umi-test` 而不是 `umi test`，umi 没有 test 命令
