### ISSUE TITLE
bug: [BABEL] /.umirc.ts: You gave us a visitor for the node type TSInstantiationExpression but it's not a valid type

### ISSUE THREAD

**Issue by Mcalready** [umijs/dumi#1093]
今天构建和启动的时候突然出现以下错误，排查了很久没找到是什么原因，麻烦帮忙看看可能是什么原因呢：

[BABEL] /.umirc.ts: You gave us a visitor for the node type TSInstantiationExpression but it's not a valid type
Error: [BABEL] /.umirc.ts: You gave us a visitor for the node type TSInstantiationExpression but it's not a valid type
    at verify (/node_modules/@umijs/deps/compiled/babel/bundle.js:61959:13)
    at Function.explode (/node_modules/@umijs/deps/compiled/babel/bundle.js:61881:3)
    at /node_modules/@umijs/deps/compiled/babel/bundle.js:2691:42
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/node_modules/@umijs/deps/compiled/babel/bundle.js:4293:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/node_modules/@umijs/deps/compiled/babel/bundle.js:121025:28)
    at Function.sync (/node_modules/@umijs/deps/compiled/babel/bundle.js:120863:14)
    at sync (/node_modules/@umijs/deps/compiled/babel/bundle.js:4333:25)
    at sync (/node_modules/@umijs/deps/compiled/babel/bundle.js:120956:19)

### Versions

- dumi: v1.1.0
- node: v12.22.5
- npm: v6.14.14
- OS: Linux
- Browser: chrome

**Comment by PeachScript** [comment]
ref: https://github.com/babel/babel/issues/14322

**Comment by fredpiuma** [comment]
Seems to be a Next problem. Every project with Next is getting this error for the last 2 days.

**Comment by Mcalready** [comment]
找到问题了，babel最近更新了版本@7.18.0。需要将babel和其所有周边插件都降级处理为@7.18.0以下
