### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by TrumanDu** [umijs/dumi#1185]
使用如下命令：
`$ npx @umijs/create-dumi-lib --site`
创建项目后，直接编译，就会报如下错误：
```
E:\demo\demo\node_modules\father\node_modules\@umijs\utils\compiled\pkg-up\index.js:1
(function (exports, require, module, __filename, __dirname) { (function(){"use strict";var e={};!function(){e.d=function(t,n){for(var r in n){if(e.o(n,r)&&!e.o(t,r)){Object.defineProperty(t,r,{enumerable:true,get:n[r]})}}}}();!function(){e.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)}}();!function(){e.r=function(e){if(typeof Symbol!=="undefined"&&Symbol.toStringTag){Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})}Object.defineProperty(e,"__esModule",{value:true})}}();if(typeof e!=="undefined")e.ab=__dirname+"/";var t={};e.r(t);e.d(t,{pkgUp:function(){return pkgUp},pkgUpSync:function(){return pkgUpSync}});var n=require("path");var r=require("url");var c=require("process");var i=require("fs");class Node{value;next;constructor(e){this.value=e}}class Queue{#e;#t;#n;constructor(){this.clear()}enqueue(e){const t=new Node(e);if(this.#e){this.#t.next=t;this.#t=t}else{this.#e=t;this.#t=t}this.#n++}d

SyntaxError: Unexpected token ;
    at new Script (vm.js:80:7)
    at NativeCompileCache._moduleCompile (E:\demo\demo\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (E:\demo\demo\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (E:\demo\demo\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (E:\demo\demo\node_modules\father\node_modules\@umijs\utils\dist\index.js:71:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo@1.0.0 build: `father build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the demo@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by PeachScript** [comment]
复现不了，检查 Node.js 版本是不是 14+
