### ISSUE TITLE
bug: 在示例中使用< img />报错

### ISSUE THREAD

**Issue by Iixianjie** [umijs/dumi#128]
### Versions

- dumi: ^1.0.9
- node: 10.15.1
- npm: 6.4.0
- OS: windows 10
- Browser: chrome

### Steps to reproduce
1. 使用code导入示例
```js
## 基础示例
<code src="./carousel-demo.tsx" />
```
2. 示例中导入本地图片
```js
import img1 from '../../../mock/img/1.jpg';

console.log(img1); // 这里正常打印了地址 /static/xx

// 使用
<img src={img1} alt="" style={{ width: '100%', height: '200px', objectFit: 'cover' }} />
```

### What is actually happening?
```shell
Module build failed (from ./node_modules/@umijs/preset-dumi/lib/loader/index.js):
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at node.value.node.value.replace.tag (C:\Users\lee\Desktop\demo\node_modules\@umijs\preset-dumi\lib\transformer\remark\img.js:64:58)
    at String.replace (<anonymous>)
    at node (C:\Users\lee\Desktop\demo\node_modules\@umijs\preset-dumi\lib\transformer\remark\img.js:54:33)
    at overload (C:\Users\lee\Desktop\demo\node_modules\@umijs\preset-dumi\node_modules\unist-util-visit\index.js:27:12)
    at one (C:\Users\lee\Desktop\demo\node_modules\unist-util-visit-parents\index.js:34:25)
    at all (C:\Users\lee\Desktop\demo\node_modules\unist-util-visit-parents\index.js:57:16)
    at one (C:\Users\lee\Desktop\demo\node_modules\unist-util-visit-parents\index.js:42:28)
    at all (C:\Users\lee\Desktop\demo\node_modules\unist-util-visit-parents\index.js:57:16)
    at one (C:\Users\lee\Desktop\demo\node_modules\unist-util-visit-parents\index.js:42:28)
    at visitParents (C:\Users\lee\Desktop\demo\node_modules\unist-util-visit-parents\index.js:26:3)
    at visit (C:\Users\lee\Desktop\demo\node_modules\@umijs\preset-dumi\node_modules\unist-util-visit\index.js:22:3)
    at ast (C:\Users\lee\Desktop\demo\node_modules\@umijs\preset-dumi\lib\transformer\remark\img.js:52:35)
    at wrapped (C:\Users\lee\Desktop\demo\node_modules\trough\wrap.js:25:19)
    at next (C:\Users\lee\Desktop\demo\node_modules\trough\index.js:57:24)

```

**Comment by PeachScript** [comment]
v1.0.10 已修复
