### ISSUE TITLE
Error: invalid type: JsValue(Function(plugin)), expected any value

### ISSUE THREAD

**Issue by hututuhu** [umijs/dumi#1369]
### Question
按照dumi官方文档创建dumi文档项目，yarn 以及yarn start之后，报错（没有添加其他内容）
### Sample Code
node版本：v16.15.1

`
Fallback bindings does not support legacy plugins, it'll be ignored.
error - ./src/Foo/index.md?type=meta
Module build failed (from ./node_modules/dumi/dist/loaders/markdown/index.js):
Error: invalid type: JsValue(Function(plugin)), expected any value     
    at module.exports.__wbindgen_error_new (D:\mydata\blog-components\node_modules\@swc\wasm\wasm.js:442:17)
    at wasm://wasm/04d64ace:wasm-function[13084]:0xe45b0c
    at wasm://wasm/04d64ace:wasm-function[5773]:0xbea711
    at wasm://wasm/04d64ace:wasm-function[2759]:0x9a755c
    at wasm://wasm/04d64ace:wasm-function[238]:0x2ba6f8
    at wasm://wasm/04d64ace:wasm-function[178]:0x221c01
    at wasm://wasm/04d64ace:wasm-function[16250]:0xea6318
    at Object.module.exports.transformSync (D:\mydata\blog-components\node_modules\@swc\wasm\wasm.js:333:14)
    at Compiler.transformSync (D:\mydata\blog-components\node_modules\@swc\core\index.js:248:37)
    at transformSync (D:\mydata\blog-components\node_modules\@swc\core\index.js:348:21)
error - ./src/Foo/index.md
Module build failed (from ./node_modules/dumi/dist/loaders/markdown/index.js):
Error: invalid type: JsValue(Function(plugin)), expected any value     
    at module.exports.__wbindgen_error_new (D:\mydata\blog-components\node_modules\@swc\wasm\wasm.js:442:17)
    at wasm://wasm/04d64ace:wasm-function[13084]:0xe45b0c
    at wasm://wasm/04d64ace:wasm-function[5773]:0xbea711
    at wasm://wasm/04d64ace:wasm-function[2759]:0x9a755c
    at wasm://wasm/04d64ace:wasm-function[238]:0x2ba6f8
    at wasm://wasm/04d64ace:wasm-function[178]:0x221c01
    at wasm://wasm/04d64ace:wasm-function[16250]:0xea6318
    at Object.module.exports.transformSync (D:\mydata\blog-components\node_modules\@swc\wasm\wasm.js:333:14)  
    at Compiler.transformSync (D:\mydata\blog-components\node_modules\@swc\core\index.js:248:37)
    at transformSync (D:\mydata\blog-components\node_modules\@swc\core\index.js:348:21)
`
![image](https://user-images.githubusercontent.com/37233828/206985684-d6651b81-89fa-4c8f-bee2-dbe534a8c36b.png)

**Comment by Fa-haxiki** [comment]
+1

**Comment by PeachScript** [comment]
我用 yarn 试了下是 OK 的， @hututuhu @Fa-haxiki 两位的设备是 Windows 系统么，方便的话帮忙排查下原因？

如果是近期才出现的，那么可能和这条 commit 有关系：https://github.com/umijs/dumi/commit/69c130bbbcdccd987e4a5e50937f0304a6167152

**Comment by Fa-haxiki** [comment]
已经解决了，是windows下缺失了一个c++库，具体解决方案在这https://github.com/swc-project/swc/issues/1351#issuecomment-1283551742
