### ISSUE TITLE
feat: support phantomDependency

### ISSUE THREAD

**Issue by afc163** [umijs/dumi#1402]
umi 中有了，但是 dumi 不支持：https://github.com/umijs/umi/pull/10183

<img width="1010" alt="图片" src="https://user-images.githubusercontent.com/507615/210768863-14699498-ef1f-4ed4-8756-7ee8d0f2520c.png">

```
info  - dumi v2.0.18
fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: phantomDependency
    at Function.validateConfig (/Users/afc163/Projects/ant-design/node_modules/@umijs/core/dist/config/config.js:182:31)
    at Config.getConfig (/Users/afc163/Projects/ant-design/node_modules/@umijs/core/dist/config/config.js:60:12)
    at DumiService.resolveConfig (/Users/afc163/Projects/ant-design/node_modules/@umijs/core/dist/service/service.js:286:97)
    at DumiService.run (/Users/afc163/Projects/ant-design/node_modules/@umijs/core/dist/service/service.js:235:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DumiService.run2 (/Users/afc163/Projects/ant-design/node_modules/umi/dist/service/service.js:58:12)
    at async /Users/afc163/Projects/ant-design/node_modules/dumi/dist/service/forkedDev.js:24:5 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
fatal - A complete log of this run can be found in:
fatal - /Users/afc163/Projects/ant-design/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
```

**Comment by PeachScript** [comment]
试了下是可以的，会不会 `node_modules` 下 umi 的版本还是旧的
