### ISSUE TITLE
bug: Linux环境两层以上引用找不到文件

### ISSUE THREAD

**Issue by Evanna51** [umijs/dumi#143]
### Versions

- dumi: 1.0.7
- node: 8.16.2
- npm: 6.4.2
- OS: Ubuntu18.04 LTS

### Steps to reproduce
目录结构如下
/docs
--/demo
----/css
------/Grid
--------index.jsx
--/tech
----/css
------css.md （`<code src="../../demo/css/Grid/index.jsx" />`）
--index.html

在windows系统中均能打包/构建成功，linux下均不成功
报错信息为：
```shell
[External-Demo Error]: cannot find demo in /root/blog/docs/demo/css/Grid/index.jsx
Error: [External-Demo Error]: cannot find demo in /root/blog/docs/demo/css/Grid/index.jsx
    at forEach.tag (/root/blog/node_modules/@umijs/preset-dumi/lib/transformer/remark/externalDemo.js:150:21)
    at Array.forEach (<anonymous>)
    at /root/blog/node_modules/@umijs/preset-dumi/lib/transformer/remark/externalDemo.js:115:22
...
```

**Comment by PeachScript** [comment]
升级到最新版本试试看

**Comment by Evanna51** [comment]
> 升级到最新版本试试看

Windows和linux同时更新到1.0.15， Windows仍旧没有问题，Ubuntu仍旧报错，报错信息更新为：

```
ERROR [dumi]: cannot resolve module ../../demo/css/Grid/index.jsx from /root/blog/docs/tech/css/ccs.md
Can't resolve '../../demo/css/Grid/index.jsx' in '/root/blog/docs/tech/css'
Error: Can't resolve '../../demo/css/Grid/index.jsx' in '/root/blog/docs/tech/css'
  at doResolve (/root/blog/node_modules/enhanced-resolve/lib/Resolver.js:209:21)
  at hook.callAsync (/root/blog/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
...
```

**Comment by PeachScript** [comment]
检查一下文件名大小写是否**完全一致**

**Comment by Evanna51** [comment]
> 检查一下文件名大小写是否**完全一致**

尝试了文件名全部改成小写/大写，WIndows下面打包正常，ubuntu仍旧报错，与引用层级无关。
（在windows的文件夹内，使用WSL-Ubuntu打包成功，不知道是否为两个环境的依赖不同的原因）

**Comment by Evanna51** [comment]
> 检查一下文件名大小写是否**完全一致**

抱歉，检查了一下发现是本地git服务器的问题，代码库的文件夹大小写没有更新
