### ISSUE TITLE
构建报错

### ISSUE THREAD

**Issue by DaphnisLi** [umijs/dumi#1439]
```


> dumi build
--
00:38:36.216 |  
00:38:39.979 | [info] [webpackbar] Compiling Webpack
00:38:39.994 | (node:387) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
00:38:39.995 | (Use `node --trace-deprecation ...` to show where the warning was created)
00:38:39.995 | (node:387) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
00:38:40.200 | node:internal/crypto/hash:71
00:38:40.200 | this[kHandle] = new _Hash(algorithm, xofLen);
00:38:40.200 | ^
00:38:40.200 |  
00:38:40.200 | Error: error:0308010C:digital envelope routines::unsupported
00:38:40.201 | at new Hash (node:internal/crypto/hash:71:19)
00:38:40.201 | at Object.createHash (node:crypto:133:10)
00:38:40.201 | at BulkUpdateDecorator.hashFactory (/vercel/path0/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:184154:18)
00:38:40.201 | at BulkUpdateDecorator.digest (/vercel/path0/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:184089:21)
00:38:40.202 | at NormalModule._initBuildHash (/vercel/path0/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115965:53)
00:38:40.202 | at /vercel/path0/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:116005:10
00:38:40.202 | at processResult (/vercel/path0/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115801:12)
00:38:40.203 | at /vercel/path0/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115900:5
00:38:40.203 | at /vercel/path0/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:35125:11
00:38:40.203 | at /vercel/path0/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34977:18
00:38:40.203 | at context.callback (/vercel/path0/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34850:13)
00:38:40.203 | at /vercel/path0/node_modules/@umijs/deps/compiled/babel-loader/index.js:1:130091 {
00:38:40.204 | opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
00:38:40.204 | library: 'digital envelope routines',
00:38:40.204 | reason: 'unsupported',
00:38:40.204 | code: 'ERR_OSSL_EVP_UNSUPPORTED'
00:38:40.204 | }
00:38:40.204 |  
00:38:40.204 | Node.js v18.12.1
00:38:40.235 | Error: Command "npm run docs:build" exited with 1


```

**Comment by DaphnisLi** [comment]
已解决, node 版本太高
