### ISSUE TITLE
bug: 升级到最新版构建报错

### ISSUE THREAD

**Issue by shaodahong** [umijs/dumi#150]
### Versions

- dumi:1.0.16
- node:12.x
- npm:
- OS:
- Browser:

### Steps to reproduce

```bash
10:08:37.378  
    ERROR in ./.umi-production/core/history.ts
10:08:37.378  
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
10:08:37.378  
    SyntaxError: /zeit/48c9ad75/.umi-production/core/history.ts: Unexpected token (12:2)
10:08:37.378  
    
10:08:37.378  
      10 | let history = createBrowserHistory(options);
10:08:37.378  
      11 | export const createHistory = (hotReload = false) => {
10:08:37.378  
    > 12 |   if (!hotReload) {
10:08:37.378  
         |   ^
10:08:37.378  
      13 |     history = createBrowserHistory(options);
10:08:37.378  
      14 |   }
10:08:37.378  
      15 | 
10:08:37.378  
        at Object._raise (/zeit/48c9ad75/node_modules/@babel/parser/src/parser/location.js:241:45)
10:08:37.379  
        at Object.raiseWithData (/zeit/48c9ad75/node_modules/@babel/parser/src/parser/location.js:236:17)
10:08:37.379  
        at Object.raise (/zeit/48c9ad75/node_modules/@babel/parser/src/parser/location.js:220:17)
10:08:37.379  
        at Object.unexpected (/zeit/48c9ad75/node_modules/@babel/parser/src/parser/util.js:149:16)
```

项目地址：https://github.com/shaodahong/antd-coffee
升级PR: https://github.com/shaodahong/antd-coffee/pull/24

**Comment by shaodahong** [comment]
本地 `babel.config.js` 会和 dumi build 冲突

**Comment by PeachScript** [comment]
dumi (umi) 会读取用户的 babel 配置，用 BABEL_ENV 做下区分看看，比如 BABEL_ENV 为 doc 的时候不挂载额外的配置，用 dumi 默认的即可
