### ISSUE TITLE
MODULE_0___default(...) is not a function

### ISSUE THREAD

**Issue by Silence-dream** [umijs/dumi#1584]
### Question

这个报错我不知道如何解决,复现条件还没有找到,想请问一下有办法解决吗?

### Sample Code
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/42824008/228422458-2a23a2cc-2d13-4097-a897-21e0537f5e00.png">

```sh

TypeError: mf_Users_silence_Documents_01MyCode_02_lowcode_platform_ui_components_node_modules_pnpm_registry_npmmirror_com_umijs_utils_4_0_63_node_modules_umijs_utils_compiled_strip_ansi_index_js__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function
    at handleWarnings (client.js:169:1)
    at _callee4$ (client.js:281:1)
    at tryCatch (client.js:2:1)
    at Generator.<anonymous> (client.js:2:1)
    at Generator.next (client.js:2:1)
    at asyncGeneratorStep (client.js:3:1)
    at _next (client.js:4:1)
    at client.js:4:1
    at new Promise (<anonymous>)
    at client.js:4:1
    at handleMessage (client.js:261:1)
    at _callee$ (client.js:50:1)
    at tryCatch (client.js:2:1)
    at Generator.<anonymous> (client.js:2:1)
    at Generator.next (client.js:2:1)
    at asyncGeneratorStep (client.js:3:1)
    at _next (client.js:4:1)
    at client.js:4:1
    at new Promise (<anonymous>)
    at WebSocket.<anonymous> (client.js:4:1)
    at WebSocket.<anonymous> (client.js:59:1)
```

**Comment by PeachScript** [comment]
没有稳定复现无法排查，可以尝试创建最小可复现仓库再按照 bug 反馈模板提交 issue
