### ISSUE TITLE
bug: umijs_utils_compiled_strip_ansi_index_js__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function

### ISSUE THREAD

**Issue by Silence-dream** [umijs/dumi#1587]
### Versions

- dumi:2.1.17
- umi: 4.0.61
- node: 18.15.0
- npm: 9.5.1
- OS: macOS 13.2.1
- Browser:

```sh
  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 88.17 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 16.3
```

### What is Expected?

预期没有报错.

### 复现步骤

```sh
# 先找个地方建个空目录。
$ mkdir myapp && cd myapp

# 通过官方工具创建项目，选择React Library
$ npx create-dumi

```

然后在 package.json 添加 ` "type": "module"`

<img width="969" alt="image" src="https://user-images.githubusercontent.com/42824008/228721001-81d6bc4d-3014-48e7-afca-64fd45ad1a88.png">

清理 node_modules
重新安装依赖

```sh
npm dev
```

即可复现问题

报错信息如下: 
```sh
TypeError: mf_Users_silence_Documents_01MyCode_test_dumi_test_node_modules_pnpm_umijs_utils_4_0_63_node_modules_umijs_utils_compiled_strip_ansi_index_js__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function
    at handleWarnings (client.js:169:1)
    at _callee4$ (client.js:281:1)
    at tryCatch (client.js:2:1)
    at Generator.<anonymous> (client.js:2:1)
    at Generator.next (client.js:2:1)
    at asyncGeneratorStep (client.js:3:1)
    at _next (client.js:4:1)
    at client.js:4:1
    at new Promise (<anonymous>)
    at client.js:4:1
    at handleMessage (client.js:261:1)
    at _callee$ (client.js:50:1)
    at tryCatch (client.js:2:1)
    at Generator.<anonymous> (client.js:2:1)
    at Generator.next (client.js:2:1)
    at asyncGeneratorStep (client.js:3:1)
    at _next (client.js:4:1)
    at client.js:4:1
    at new Promise (<anonymous>)
    at WebSocket.<anonymous> (client.js:4:1)
    at WebSocket.<anonymous> (client.js:59:1)
console.<computed> @ mf-dep____vendor.7e2f2127.async.js:16067
```

### What is actually happening?

![image](https://user-images.githubusercontent.com/42824008/228720190-692c62dc-2d7e-49af-95c5-f1bb4e4b16bb.png)

**Comment by PeachScript** [comment]
MFSU 暂时不能和 pure esm 项目正常工作，v2.1.18 已对 pure esm 默认关闭 MFSU
