### ISSUE TITLE
bug:  dumi 2.1.20 开启 mfsu 后启动报错

### ISSUE THREAD

**Issue by Col0ring** [umijs/dumi#1612]
### Versions

- dumi: 2.1.20
- node: v16.15.1
- npm: pnpm 8.2.0
- OS: Mac OS
- Browser: Edge

### Steps to reproduce
跑官网的初始化步骤，使用`pnpm update --interactive --latest`将所有依赖更新到最新，运行。
### What is Expected?
可以正常启动。
### What is actually happening?
启动报错：
```text
error - ./.dumi/tmp/core/route.tsx
Module build failed (from ./node_modules/.pnpm/@umijs+bundler-webpack@4.0.65_styled-components@5.3.9_typescript@5.0.4_webpack@5.79.0/node_modules/@umijs/bundler-webpack/compiled/babel-loader/index.js):
TypeError: /Users/coloring/workspace/personal/demo/dumi-demo/.dumi/tmp/core/route.tsx: value.endsWith is not a function
    at addLastSlash (/Users/coloring/workspace/personal/demo/dumi-demo/node_modules/.pnpm/@umijs+utils@4.0.65/node_modules/@umijs/utils/dist/aliasUtils/getAliasValue.js:57:16)
    at Object.getAliasValue (/Users/coloring/workspace/personal/demo/dumi-demo/node_modules/.pnpm/@umijs+utils@4.0.65/node_modules/@umijs/utils/dist/aliasUtils/getAliasValue.js:52:49)
```
貌似是  mfsu 的问题，手动将 mfsu 置为 false 后能正常运行。

**Comment by PeachScript** [comment]
v2.1.21 已修复
