### ISSUE TITLE
bug: 使用dumi封装antd组件报错

### ISSUE THREAD

**Issue by NancysMom** [umijs/dumi#1718]
### Versions

- dumi:2.20
- node:
- npm:
- OS:
- Browser:google

### Steps to reproduce
1、创建dumi 组件库项目
2、导出antd button组件
3、构建发包
4、安装使用

### What is Expected?
button组件正常渲染

### What is actually happening?
index.js:1 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
console.<computed> @ index.js:1
printWarning @ mf-dep____vendor.48099876.js:245268
error @ mf-dep____vendor.48099876.js:245242
resolveDispatcher @ mf-dep____vendor.48099876.js:246651
useContext @ mf-dep____vendor.48099876.js:246661
InternalButton @ button.js:111
renderWithHooks @ mf-dep____vendor.48099876.js:225304
updateForwardRef @ mf-dep____vendor.48099876.js:229147
beginWork @ mf-dep____vendor.48099876.js:231589
beginWork$1 @ mf-dep____vendor.48099876.js:236505
performUnitOfWork @ mf-dep____vendor.48099876.js:235637
workLoopSync @ mf-dep____vendor.48099876.js:235546
renderRootSync @ mf-dep____vendor.48099876.js:235514
recoverFromConcurrentError @ mf-dep____vendor.48099876.js:234930
performConcurrentWorkOnRoot @ mf-dep____vendor.48099876.js:234830
workLoop @ mf-dep____vendor.48099876.js:250302
flushWork @ mf-dep____vendor.48099876.js:250275
performWorkUntilDeadline @ mf-dep____vendor.48099876.js:250569
queue.<computed> @ mf-dep____vendor.48099876.js:135487
run @ mf-dep____vendor.48099876.js:135461
listener @ mf-dep____vendor.48099876.js:135472
index.js:1 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
console.<computed> @ index.js:1
printWarning @ mf-dep____vendor.48099876.js:245268
error @ mf-dep____vendor.48099876.js:245242
resolveDispatcher @ mf-dep____vendor.48099876.js:246651
useContext @ mf-dep____vendor.48099876.js:246661
InternalButton @ button.js:111
renderWithHooks @ mf-dep____vendor.48099876.js:225304
updateForwardRef @ mf-dep____vendor.48099876.js:229147
beginWork @ mf-dep____vendor.48099876.js:231589
callCallback @ mf-dep____vendor.48099876.js:213290
invokeGuardedCallbackDev @ mf-dep____vendor.48099876.js:213339
invokeGuardedCallback @ mf-dep____vendor.48099876.js:213403
beginWork$1 @ mf-dep____vendor.48099876.js:236529
performUnitOfWork @ mf-dep____vendor.48099876.js:235637
workLoopSync @ mf-dep____vendor.48099876.js:235546
renderRootSync @ mf-dep____vendor.48099876.js:235514
recoverFromConcurrentError @ mf-dep____vendor.48099876.js:234930
performConcurrentWorkOnRoot @ mf-dep____vendor.48099876.js:234830
workLoop @ mf-dep____vendor.48099876.js:250302
flushWork @ mf-dep____vendor.48099876.js:250275
performWorkUntilDeadline @ mf-dep____vendor.48099876.js:250569
queue.<computed> @ mf-dep____vendor.48099876.js:135487
run @ mf-dep____vendor.48099876.js:135461
listener @ mf-dep____vendor.48099876.js:135472
mf-dep____vendor.48099876.js:246677 Uncaught TypeError: Cannot read property 'useContext' of null
    at Object.useContext (mf-dep____vendor.48099876.js:246677)
    at InternalButton (button.js:111)
    at renderWithHooks (mf-dep____vendor.48099876.js:225304)
    at updateForwardRef (mf-dep____vendor.48099876.js:229147)
    at beginWork (mf-dep____vendor.48099876.js:231589)
    at HTMLUnknownElement.callCallback (mf-dep____vendor.48099876.js:213290)
    at Object.invokeGuardedCallbackDev (mf-dep____vendor.48099876.js:213339)
    at invokeGuardedCallback (mf-dep____vendor.48099876.js:213403)
    at beginWork$1 (mf-dep____vendor.48099876.js:236529)
    at performUnitOfWork (mf-dep____vendor.48099876.js:235637)
    at workLoopSync (mf-dep____vendor.48099876.js:235546)
    at renderRootSync (mf-dep____vendor.48099876.js:235514)
    at recoverFromConcurrentError (mf-dep____vendor.48099876.js:234930)
    at performConcurrentWorkOnRoot (mf-dep____vendor.48099876.js:234830)
    at workLoop (mf-dep____vendor.48099876.js:250302)
    at flushWork (mf-dep____vendor.48099876.js:250275)
    at performWorkUntilDeadline (mf-dep____vendor.48099876.js:250569)
    at queue.<computed> (mf-dep____vendor.48099876.js:135487)
    at run (mf-dep____vendor.48099876.js:135461)
    at MessagePort.listener (mf-dep____vendor.48099876.js:135472)
useContext @ mf-dep____vendor.48099876.js:246677
InternalButton @ button.js:111
renderWithHooks @ mf-dep____vendor.48099876.js:225304
updateForwardRef @ mf-dep____vendor.48099876.js:229147
beginWork @ mf-dep____vendor.48099876.js:231589
callCallback @ mf-dep____vendor.48099876.js:213290
invokeGuardedCallbackDev @ mf-dep____vendor.48099876.js:213339
invokeGuardedCallback @ mf-dep____vendor.48099876.js:213403
beginWork$1 @ mf-dep____vendor.48099876.js:236529
performUnitOfWork @ mf-dep____vendor.48099876.js:235637
workLoopSync @ mf-dep____vendor.48099876.js:235546
renderRootSync @ mf-dep____vendor.48099876.js:235514
recoverFromConcurrentError @ mf-dep____vendor.48099876.js:234930
performConcurrentWorkOnRoot @ mf-dep____vendor.48099876.js:234830
workLoop @ mf-dep____vendor.48099876.js:250302
flushWork @ mf-dep____vendor.48099876.js:250275
performWorkUntilDeadline @ mf-dep____vendor.48099876.js:250569
queue.<computed> @ mf-dep____vendor.48099876.js:135487
run @ mf-dep____vendor.48099876.js:135461
listener @ mf-dep____vendor.48099876.js:135472
index.js:1 The above error occurred in the <Button> component:

    at InternalButton (http://localhost:8000/vendors-node_modules_antd-components_es_index_js.async.js:2018:30)
    at div
    at div
    at div
    at div
    at GridContent (http://localhost:8000/mf-dep____vendor.48099876.js:66221:64)
    at div
    at PageContainerBase (http://localhost:8000/mf-dep____vendor.48099876.js:66709:24)
    at ProConfigProvider (http://localhost:8000/mf-dep____vendor.48099876.js:72890:24)
    at PageContainer
    at HomePage (http://localhost:8000/p__Home__index.async.js:177:71)
    at Suspense
    at RemoteComponent (http://localhost:8000/mf-dep____vendor.48099876.js:93101:25)
    at Outlet (http://localhost:8000/mf-dep____vendor.48099876.js:240631:26)
    at Exception (http://localhost:8000/umi__plugin-layout__Layout.async.js:34:12)
    at main
    at http://localhost:8000/mf-dep____vendor.48099876.js:106982:25
    at Content (http://localhost:8000/mf-dep____vendor.48099876.js:106965:66)
    at ErrorBoundary (http://localhost:8000/mf-dep____vendor.48099876.js:81950:90)
    at WrapContent (http://localhost:8000/mf-dep____vendor.48099876.js:64502:70)
    at div
    at section
    at http://localhost:8000/mf-dep____vendor.48099876.js:106996:63
    at Layout (http://localhost:8000/mf-dep____vendor.48099876.js:106965:66)
    at div
    at BaseProLayout (http://localhost:8000/mf-dep____vendor.48099876.js:64163:13)
    at ProviderChildren (http://localhost:8000/mf-dep____vendor.48099876.js:101102:24)
    at LocaleReceiver (http://localhost:8000/mf-dep____vendor.48099876.js:107493:36)
    at ConfigProvider (http://localhost:8000/mf-dep____vendor.48099876.js:101205:13)
    at div
    at SWRConfig (http://localhost:8000/mf-dep____vendor.48099876.js:255110:13)
    at ConfigProVidContainer (http://localhost:8000/mf-dep____vendor.48099876.js:72787:24)
    at FormProvider (http://localhost:8000/mf-dep____vendor.48099876.js:168025:31)
    at LocaleProvider (http://localhost:8000/mf-dep____vendor.48099876.js:107582:29)
    at ProviderChildren (http://localhost:8000/mf-dep____vendor.48099876.js:101102:24)
    at LocaleReceiver (http://localhost:8000/mf-dep____vendor.48099876.js:107493:36)
    at ConfigProvider (http://localhost:8000/mf-dep____vendor.48099876.js:101205:13)
    at ProConfigProvider (http://localhost:8000/mf-dep____vendor.48099876.js:72890:24)
    at ProviderChildren (http://localhost:8000/mf-dep____vendor.48099876.js:101102:24)
    at LocaleReceiver (http://localhost:8000/mf-dep____vendor.48099876.js:107493:36)
    at ConfigProvider (http://localhost:8000/mf-dep____vendor.48099876.js:101205:13)
    at ProLayout (http://localhost:8000/mf-dep____vendor.48099876.js:64450:28)
    at http://localhost:8000/umi__plugin-layout__Layout.async.js:208:66
    at Suspense
    at RemoteComponent (http://localhost:8000/mf-dep____vendor.48099876.js:93101:25)
    at Routes (http://localhost:8000/mf-dep____vendor.48099876.js:92614:76)
    at Router (http://localhost:8000/mf-dep____vendor.48099876.js:240654:15)
    at BrowserRoutes (http://localhost:8000/mf-dep____vendor.48099876.js:92572:23)
    at Provider (http://localhost:8000/src_umi_umi_ts.async.js:1510:74)
    at InitialStateProvider (http://localhost:8000/src_umi_umi_ts.async.js:1761:101)
    at Provider (http://localhost:8000/src_umi_umi_ts.async.js:2157:34)
    at ProviderWrapper (http://localhost:8000/src_umi_umi_ts.async.js:2365:98)
    at HelmetProvider (http://localhost:8000/mf-dep____vendor.48099876.js:239155:7350)
    at Browser (http://localhost:8000/mf-dep____vendor.48099876.js:92687:68)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.

**Comment by PeachScript** [comment]
React 多实例了，发包后的问题需要自行排查原因，一般两种可能性，仅供参考：
1. umd 产物把 react 一起打包了，需要做 externals
2. 非 umd 产物但声明的 react 版本与项目的 react 不在同一个 range，需要根据需要匹配版本号声明
