### ISSUE TITLE
monorepoRedirect报错

### ISSUE THREAD

**Issue by AllenJacen** [umijs/dumi#1732]
### Question
AssertionError [ERR_ASSERTION]: The 'monorepoRedirect' option can only be used in monorepo, you don't need configure.
### Sample Code
一个monorepo的项目
配置了
```ts
 monorepoRedirect: {
    peerDeps: true,
    srcDir: ['libs', 'src'],
  },
```
报错信息：
```ts
fatal - AssertionError [ERR_ASSERTION]: The 'monorepoRedirect' option can only be used in monorepo, you don't need configure.
    at Hook.fn (/Users/tech-code/xx/node_modules/@umijs/preset-umi/dist/features/monorepo/redirect.js:67:31)
    at async /Users/tech-code/xx/node_modules/@umijs/core/dist/service/service.js:136:27 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
```

```
dumi@2.2.0
lerna@4.0.0
```

**Comment by AllenJacen** [comment]
1
