### ISSUE TITLE
运行 dumi dev 报错

### ISSUE THREAD

**Issue by coder-fang** [umijs/dumi#1738]
### Question
运行 dumi dev 后，报错：

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports.__webpack_modules__.57442.module.exports (/workspace/AoneUI/packages/docs/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:135907:62)
    at NormalModule._initBuildHash (/workspace/AoneUI/packages/docs/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:109317:16)
    at /workspace/AoneUI/packages/docs/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:109352:10
    at /workspace/AoneUI/packages/docs/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:109223:13
    at /workspace/AoneUI/packages/docs/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:61151:11
    at /workspace/AoneUI/packages/docs/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:61017:18
    at context.callback (/workspace/AoneUI/packages/docs/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:60895:13)
    at /workspace/AoneUI/packages/docs/node_modules/.pnpm/@umijs+deps@3.5.41/node_modules/@umijs/deps/compiled/babel-loader/index.js:1:130029 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
### Sample Code
使用的dumi版本："dumi": "^1.1.50"

**Comment by coder-fang** [comment]
把dumi升级到`v2.2.1` 就行了。
