### ISSUE TITLE
bug: 启动报错

### ISSUE THREAD

**Issue by LeongLRF** [umijs/dumi#1743]
### Versions

- dumi: 最新版
- node: 16.14.0
- npm: 9.2.0
- OS: linux
- Browser: --

### Steps to reproduce
npm start

### What is Expected?
正常启动
### What is actually happening?
启动报错
`node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/workspace/demo/package.json'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2249:34)
    at createFsWatchInstance (/home/workspace/demo/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/workspace/demo/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/workspace/demo/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/workspace/demo/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/home/workspace/demo/node_modules/chokidar/lib/nodefs-handler.js:637:21)
    at async /home/workspace/demo/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/home/workspace/demo/node_modules/chokidar/index.js:647:10)
    at NodeFsHandler._addToNodeFs (/home/workspace/demo/node_modules/chokidar/lib/nodefs-handler.js:645:18)
    at async /home/workspace/demo/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/workspace/demo/package.json',
  filename: '/home/workspace/demo/package.json'
}`

**Comment by PeachScript** [comment]
遇到标准库报错先搜索引擎寻找答案，参考：https://stackoverflow.com/a/55763478
