### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by Chasen-Zhang** [umijs/dumi#1759]
### Question

$ husky install && dumi setup
husky - Git hooks installed
info  - dumi v2.2.1
fatal - Error: Register plugin /home/runner/work/x-ui/x-ui/node_modules/dumi/dist/features/autoAlias.js failed, since Cannot find module './util'
Require stack:
- /home/runner/work/x-ui/x-ui/node_modules/dumi/node_modules/file-system-cache/lib/common/index.js
- /home/runner/work/x-ui/x-ui/node_modules/dumi/node_modules/file-system-cache/lib/FileSystemCache.js
- /home/runner/work/x-ui/x-ui/node_modules/dumi/node_modules/file-system-cache/lib/index.js
- /home/runner/work/x-ui/x-ui/node_modules/dumi/dist/utils.js
- /home/runner/work/x-ui/x-ui/node_modules/dumi/dist/features/autoAlias.js
- /home/runner/work/x-ui/x-ui/node_modules/@umijs/core/dist/service/plugin.js
- /home/runner/work/x-ui/x-ui/node_modules/@umijs/core/dist/service/pluginAPI.js
- /home/runner/work/x-ui/x-ui/node_modules/@umijs/core/dist/index.js
- /home/runner/work/x-ui/x-ui/node_modules/dumi/dist/service/service.js
- /home/runner/work/x-ui/x-ui/node_modules/dumi/dist/service/cli.js
- /home/runner/work/x-ui/x-ui/node_modules/dumi/dist/cli.js
- /home/runner/work/x-ui/x-ui/node_modules/dumi/bin/dumi.js
    at Plugin.apply (/home/runner/work/x-ui/x-ui/node_modules/@umijs/core/dist/service/plugin.js:76:15)
    at DumiService.initPlugin (/home/runner/work/x-ui/x-ui/node_modules/@umijs/core/dist/service/service.js:4[63](https://github.com/databendcloud/x-ui/actions/runs/5387286039/jobs/9778399051#step:4:64):33)
    at DumiService.run (/home/runner/work/x-ui/x-ui/node_modules/@umijs/core/dist/service/service.js:259:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DumiService.run2 (/home/runner/work/x-ui/x-ui/node_modules/umi/dist/service/service.js:65:12)
    at async run (/home/runner/work/x-ui/x-ui/node_modules/dumi/dist/service/cli.js:57:7)
    at async /home/runner/work/x-ui/x-ui/node_modules/dumi/dist/cli.js:23:5 {
  [cause]: Error: Cannot find module './util'
  Require stack:
  - /home/runner/work/x-ui/x-ui/node_modules/dumi/node_modules/file-system-cache/lib/common/index.js
  - /home/runner/work/x-ui/x-ui/node_modules/dumi/node_modules/file-system-cache/lib/FileSystemCache.js
  - /home/runner/work/x-ui/x-ui/node_modules/dumi/node_modules/file-system-cache/lib/index.js
  - /home/runner/work/x-ui/x-ui/node_modules/dumi/dist/utils.js
  - /home/runner/work/x-ui/x-ui/node_modules/dumi/dist/features/autoAlias.js
  - /home/runner/work/x-ui/x-ui/node_modules/@umijs/core/dist/service/plugin.js
  - /home/runner/work/x-ui/x-ui/node_modules/@umijs/core/dist/service/pluginAPI.js
  - /home/runner/work/x-ui/x-ui/node_modules/@umijs/core/dist/index.js
  - /home/runner/work/x-ui/x-ui/node_modules/dumi/dist/service/service.js
  - /home/runner/work/x-ui/x-ui/node_modules/dumi/dist/service/cli.js
  - /home/runner/work/x-ui/x-ui/node_modules/dumi/dist/cli.js
  - /home/runner/work/x-ui/x-ui/node_modules/dumi/bin/dumi.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:10[75](https://github.com/databendcloud/x-ui/actions/runs/5387286039/jobs/9778399051#step:4:76):15)
      at mod._resolveFilename (/home/runner/work/x-ui/x-ui/node_modules/umi/dist/service/requireHook.js:13:26)
      at Module._load (node:internal/modules/cjs/loader:[92](https://github.com/databendcloud/x-ui/actions/runs/5387286039/jobs/9778399051#step:4:93)0:27)
      at Module.require (node:internal/modules/cjs/loader:1141:19)
      at require (node:internal/modules/cjs/helpers:110:18)
      at Object.<anonymous> (/home/runner/work/x-ui/x-ui/node_modules/dumi/node_modules/file-system-cache/lib/common/index.js:30:27)
      at Module._compile (node:internal/modules/cjs/loader:1254:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
      at Module.load (node:internal/modules/cjs/loader:1117:32)
      at Module._load (node:internal/modules/cjs/loader:[95](https://github.com/databendcloud/x-ui/actions/runs/5387286039/jobs/9778399051#step:4:96)8:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/home/runner/work/x-ui/x/node_modules/dumi/node_modules/file-system-cache/lib/common/index.js',
  }
}
fatal - A complete log of this run can be found in:
fatal - /home/runner/work/x-ui/x-ui/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/dumi/issues
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

安装依赖报错

@PeachScript 你好，能否帮忙看下这个问题

**Comment by Chasen-Zhang** [comment]
"prepare": "dumi setup"   运行这个命令报错，

**Comment by Wuriqilang** [comment]
相同错误

**Comment by Chasen-Zhang** [comment]
> 

我就这两天报这个错，哥们，你解决了吗

**Comment by Chasen-Zhang** [comment]
好像他们不怎么活跃的样子，

**Comment by afc163** [comment]
可以去 https://github.com/philcockfield/file-system-cache/issues/30 这里催下。

**Comment by Chasen-Zhang** [comment]
> 可以去 [philcockfield/file-system-cache#30](https://github.com/philcockfield/file-system-cache/issues/30) 这里催下。

有没有临时的解决方案呢

**Comment by afc163** [comment]
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by Wuriqilang** [comment]
file-system-cache库 Utils文件大小写导致的问题，我的解决方案是

package.json里添加
`
  "overrides": {
    "file-system-cache": "2.3.0"
  }
`

**Comment by PeachScript** [comment]
file-system-cache 已发布修复版本 2.4.1，诸位移除临时方案再重新安装依赖即可；如果使用 pnpm 或 yarn 初始化脚手架，需要同步更新 lock 文件避免继续安装到有问题的版本

该 issue 关闭
