### ISSUE TITLE
bug:  Cannot read properties of undefined (reading 'loader')

### ISSUE THREAD

**Issue by Pursue-LLL** [umijs/dumi#1779]
设置 srcTranspiler: "esbuild"后报错

info  - dumi v2.2.1
warn  - Hash history is temporarily incompatible, it is recommended to use browser history for now.
info  - Umi v4.0.72
fatal - TypeError: Cannot read properties of undefined (reading 'loader')
    at Hook.fn (/Users/yululiu/projects/koo/daxue-design/node_modules/.pnpm/dumi@2.2.1_7kds475sccme62neo6cmtlakh4/node_modules/dumi/dist/features/compile/index.js:61:149)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/yululiu/projects/koo/daxue-design/node_modules/.pnpm/@umijs+core@4.0.72/node_modules/@umijs/core/dist/service/service.js:136:27
fatal - A complete log of this run can be found in:
fatal - /Users/yululiu/projects/koo/daxue-design/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues

node 14

**Comment by Landon-Liu** [comment]
+1 设置swc后也会报错
