### ISSUE TITLE
bug: Build 报错

### ISSUE THREAD

**Issue by Dogtiti** [umijs/dumi#1913]
### Versions

- dumi: ^2.2.7
- node: v18.16.1
- npm: v9.5.1
- OS: MacOS
- Browser: Chrome

### Steps to reproduce
```
error - .dumi/tmp/core/history.ts:9:17 - TS2742: The inferred type of 'createHistory' cannot be named without a reference to '.pnpm/history@5.3.0/node_modules/history'. This is likely not portable. A type annotation is necessary.
error - .dumi/tmp/core/history.ts:9:17 - TS2742: The inferred type of 'createHistory' cannot be named without a reference to '.pnpm/history@5.3.0/node_modules/history'. This is likely not portable. A type annotation is necessary.
error - Error: Declaration generation failed.
    at getDeclarations (/Users/liurui/workspace/dogtiti/xx/node_modules/.pnpm/father@4.3.3_@types+node@20.4.7_styled-components@6.0.7_webpack@5.88.2/node_modules/father/dist/builder/bundless/dts/index.js:166:19)
    at transformFiles (/Users/liurui/workspace/dogtiti/xx/node_modules/.pnpm/father@4.3.3_@types+node@20.4.7_styled-components@6.0.7_webpack@5.88.2/node_modules/father/dist/builder/bundless/index.js:79:58)
    at async bundless (/Users/liurui/workspace/dogtiti/xx/node_modules/.pnpm/father@4.3.3_@types+node@20.4.7_styled-components@6.0.7_webpack@5.88.2/node_modules/father/dist/builder/bundless/index.js:107:19)
    at async builder (/Users/liurui/workspace/dogtiti/xx/node_modules/.pnpm/father@4.3.3_@types+node@20.4.7_styled-components@6.0.7_webpack@5.88.2/node_modules/father/dist/builder/index.js:47:25)
    at async Command.fn (/Users/liurui/workspace/dogtiti/xx/node_modules/.pnpm/father@4.3.3_@types+node@20.4.7_styled-components@6.0.7_webpack@5.88.2/node_modules/father/dist/commands/build.js:15:13)
    at async Service.run (/Users/liurui/workspace/dogtiti/xx/node_modules/.pnpm/@umijs+core@4.0.80/node_modules/@umijs/core/dist/service/service.js:328:15)
    at async Service.run2 (/Users/liurui/workspace/dogtiti/xx/node_modules/.pnpm/father@4.3.3_@types+node@20.4.7_styled-components@6.0.7_webpack@5.88.2/node_modules/father/dist/service/service.js:58:16)
    at async Object.run (/Users/liurui/workspace/dogtiti/xx/node_modules/.pnpm/father@4.3.3_@types+node@20.4.7_styled-components@6.0.7_webpack@5.88.2/node_modules/father/dist/cli/cli.js:37:9)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by PeachScript** [comment]
Duplicate of https://github.com/umijs/father/issues/710#issuecomment-1715093935

**Comment by PeachScript** [comment]
升级 father 和 dumi 到最新版即可

**Comment by Dogtiti** [comment]
@PeachScript 可以把脚手架模版也升级一下，现在默认创建出来的模版不是最新的

**Comment by PeachScript** [comment]
我这里试了下是新的，你的 create-dumi 是否是旧版本，我的初始化方式：

```bash
$ pnpm dlx create-dumi # 选 React 模板一路往下
$ cat tsconfig.json # include 里没有 .dumi/**/*
```

**Comment by Dogtiti** [comment]
我大概知道了，可能是我前段时间创建的项目，那时还没有升级`father`,今天再试了一下是最新的了 ，那就没问题了，多谢
