### ISSUE TITLE
bug: 升级dumi@2.x后antd@3.x编译不通过，疑似less-loader版本太高，怎么解决？

### ISSUE THREAD

**Issue by artdong** [umijs/dumi#1937]
### Version

dumi@2.x

### OS Version

Windows 10

### Node.js Version

18.4.0

### Browser Version

Chrome@117.0.5938.92

### Link to minimal reproduction

https://gitee.com/ipr-fe/knk/tree/feat-dumi-v2.x

### Steps to reproduce

yarn

yarn start

### What is expected?

样式正常编译

### What is actually happening?

Error evaluating function `max`: Operation on an invalid type
      Error in E:\gitee\knk\node_modules\antd\es\form\style\index.less (line 87, column 19)
    at Object.<anonymous> (E:\gitee\knk\node_modules\@umijs\bundler-webpack\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[5].oneOf[1].use[1]!E:\gitee\knk\node_modules\@umijs\bundler-webpack\compiled\postcss-loader\index.js??ruleSet[1].rules[5].oneOf[1].use[2]!E:\gitee\knk\node_modules\@umijs\bundler-webpack\compiled\less-loader\index.js??ruleSet[1].rules[5].oneOf[1].use[3]!E:\gitee\knk\node_modules\antd\es\form\style\index.less:1:7)
    at E:\gitee\knk\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:131315:10
    at Hook.eval [as call] (eval at create (E:\gitee\knk\node_modules\@umijs\bundler-utils\compiled\tapable\index.js:1:7460), <anonymous>:7:1)

**Comment by Wxh16144** [comment]
这也太难搞了吧，不如先把组件库 antd 依赖升级上来（毕竟业务优先）其次再去倒腾文档。

但其实保持 antd3 + dumi1 也不是不可以。

**Comment by Wxh16144** [comment]
我看了你提供的 gitee 仓库地址，给你提交了一个 PR 看看能不能解决你的问题 https://gitee.com/ipr-fe/knk/pulls/26

**Comment by yoyo837** [comment]
我也是antd@3, `less-loader`最新, 没啥问题呀, 只是没有用dumi.

**Comment by artdong** [comment]
> 我看了你提供的 gitee 仓库地址，给你提交了一个 PR 看看能不能解决你的问题 https://gitee.com/ipr-fe/knk/pulls/26

我试了你的办法，style: true 改成 style: 'css', 还是报一样的错。

**Comment by artdong** [comment]
> 我也是antd@3, `less-loader`最新, 没啥问题呀, 只是没有用dumi.

我这就是dumi@2.x生成文档报错

**Comment by artdong** [comment]
> 这也太难搞了吧，不如先把组件库 antd 依赖升级上来（毕竟业务优先）其次再去倒腾文档。
> 
> 但其实保持 antd3 + dumi1 也不是不可以。

我只是想着试试dumi@2

**Comment by artdong** [comment]
> > 我试了你的办法，style: true 改成 style: 'css', 还是报一样的错。
> 
> 还要删除一个文件哈~

赞一个👍，真的可以了。
