### ISSUE TITLE
bug: plugin @umijs/plugin-analytics is already registered

### ISSUE THREAD

**Issue by shaodahong** [umijs/dumi#204]
### Versions

- dumi:1.0.27
- node:v12.16.1
- npm:6.13.4
- OS:mac 10.15.5
- Browser:null

### Steps to reproduce
Ref: https://github.com/shaodahong/antd-coffee/pull/139

`dumi dev` or `dumi build`

```
yarn run v1.22.4
$ dumi dev
plugin @umijs/plugin-analytics is already registered by /Users/shaw/Workspace/Github/antd-coffee/node_modules/@umijs/plugin-analytics/lib/index.js, plugin from /Users/shaw/Workspace/Github/antd-coffee/node_modules/@umijs/plugin-analytics/lib/index.js register failed.
Error: plugin @umijs/plugin-analytics is already registered by /Users/shaw/Workspace/Github/antd-coffee/node_modules/@umijs/plugin-analytics/lib/index.js, plugin from /Users/shaw/Workspace/Github/antd-coffee/node_modules/@umijs/plugin-analytics/lib/index.js register failed.
    at Service.registerPlugin (/Users/shaw/Workspace/Github/antd-coffee/node_modules/@umijs/core/lib/Service/Service.js:414:13)
    at Service.initPlugin (/Users/shaw/Workspace/Github/antd-coffee/node_modules/@umijs/core/lib/Service/Service.js:398:10)
    at Service.initPresetsAndPlugins (/Users/shaw/Workspace/Github/antd-coffee/node_modules/@umijs/core/lib/Service/Service.js:307:12)
    at /Users/shaw/Workspace/Github/antd-coffee/node_modules/@umijs/core/lib/Service/Service.js:221:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/shaw/Workspace/Github/antd-coffee/node_modules/@umijs/core/lib/Service/Service.js:100:103)
    at _next (/Users/shaw/Workspace/Github/antd-coffee/node_modules/@umijs/core/lib/Service/Service.js:102:194)
    at /Users/shaw/Workspace/Github/antd-coffee/node_modules/@umijs/core/lib/Service/Service.js:102:364
    at new Promise (<anonymous>)
    at /Users/shaw/Workspace/Github/antd-coffee/node_modules/@umijs/core/lib/Service/Service.js:102:97
✨  Done in 2.18s.
```

**Comment by dream-approaching** [comment]
我也遇到了  
可以先把dumi换成v1.0.26，可以正常运行

**Comment by bwqdxxg** [comment]
这个是@umijs/preset-react这个插件导致的 不知道6天前更新了啥上去 导致炸了

**Comment by PeachScript** [comment]
是 dumi 的 v1.0.27 有 bug 导致的，1.0.29 已完全修复，大家可以更新下

**Comment by shaodahong** [comment]
Resolved https://github.com/shaodahong/antd-coffee/pull/149

**Comment by EJairwin** [comment]
> 是 dumi 的 v1.0.27 有 bug 导致的，1.0.29 已完全修复，大家可以更新下

这里的脚手架好像是v1.0.7（同样的错误）：https://d.umijs.org/guide/getting-started#%E7%BB%84%E4%BB%B6%E5%BC%80%E5%8F%91%E8%84%9A%E6%89%8B%E6%9E%B6
