### ISSUE TITLE
bug: 为什么antd使用dumi搭建的官网 经常出bug，打不开

### ISSUE THREAD

**Issue by xu756** [umijs/dumi#2196]
### Version

latest

### OS Version

mac

### Node.js Version

none

### Browser Version

chrome

### Link to minimal reproduction

https://pro-editor.antdigital.dev/

### Steps to reproduce

打开官网 直接打不开，
```
enable_copy_cracked:false
inject-content-script.js:1 inject script register service success, service name is CommonService
umi.033274d4.js:6913 TypeError: (0 , h.useMatchedRoute) is not a function
    at q (4051.dbffcd50.async.js:3:20265)
    at 4051.dbffcd50.async.js:3:21230
    at Zl (umi.033274d4.js:6911:17915)
    at yc (umi.033274d4.js:6913:3183)
    at ec (umi.033274d4.js:6913:2385)
    at ks (umi.033274d4.js:6913:1918)
    at Bd (umi.033274d4.js:6913:48585)
    at Dd (umi.033274d4.js:6913:40808)
    at Jd (umi.033274d4.js:6913:40736)
    at wc (umi.033274d4.js:6913:40589)
zo @ umi.033274d4.js:6913
x.callback @ umi.033274d4.js:6913
ci @ umi.033274d4.js:6911
Yl @ umi.033274d4.js:6913
al @ umi.033274d4.js:6913
Ad @ umi.033274d4.js:6913
_d @ umi.033274d4.js:6913
yu @ umi.033274d4.js:6913
Md @ umi.033274d4.js:6913
C @ umi.033274d4.js:6936
re @ umi.033274d4.js:6936
S.<computed> @ umi.033274d4.js:6942
re @ umi.033274d4.js:6942
pe @ umi.033274d4.js:6942
umi.033274d4.js:6913 Uncaught TypeError: (0 , h.useMatchedRoute) is not a function
    at q (4051.dbffcd50.async.js:3:20265)
    at 4051.dbffcd50.async.js:3:21230
    at Zl (umi.033274d4.js:6911:17915)
    at yc (umi.033274d4.js:6913:3183)
    at ec (umi.033274d4.js:6913:2385)
    at ks (umi.033274d4.js:6913:1918)
    at Bd (umi.033274d4.js:6913:48585)
    at Dd (umi.033274d4.js:6913:40808)
    at Jd (umi.033274d4.js:6913:40736)
    at wc (umi.033274d4.js:6913:40589)
q @ 4051.dbffcd50.async.js:3
（匿名） @ 4051.dbffcd50.async.js:3
Zl @ umi.033274d4.js:6911
yc @ umi.033274d4.js:6913
ec @ umi.033274d4.js:6913
ks @ umi.033274d4.js:6913
Bd @ umi.033274d4.js:6913
Dd @ umi.033274d4.js:6913
Jd @ umi.033274d4.js:6913
wc @ umi.033274d4.js:6913
od @ umi.033274d4.js:6913
Md @ umi.033274d4.js:6913
C @ umi.033274d4.js:6936
re @ umi.033274d4.js:6936
S.<computed> @ umi.033274d4.js:6942
re @ umi.033274d4.js:6942
pe @ umi.033274d4.js:6942
pro-editor.antdigital.dev/:1 The resource https://pro-editor.antdigital.dev/docs__index.en-US.md.9f154281.chunk.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
pro-editor.antdigital.dev/:1 The resource https://pro-editor.antdigital.dev/docs__index.en-US.md.9f154281.chunk.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
pro-editor.antdigital.dev/:1 The resource https://pro-editor.antdigital.dev/docs__index.en-US.md.9f154281.chunk.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
pro-editor.antdigital.dev/:1 The resource https://pro-editor.antdigital.dev/docs__index.en-US.md.9f154281.chunk.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```
<img width="2339" alt="image" src="https://github.com/user-attachments/assets/f0906834-1f62-4b5f-9e1b-93b18d87a3e3">

### What is expected?

正常使用

### What is actually happening?

首先：本项目（dumi）确实是一个好产品
外宣：蚂蚁内部都使用我们dumi
现实：你们内部程序员都用不好dumi

最近三个月 antdprocomponents挂的次数，bud次数，我一只手也数不完，打不开，域名换来换去，加载页面，需要手动刷新才能显示，天天bug哎嘿，今天(上周末，今天9月10号了 仍然打不开) pro-editor 又双叒叕挂了

一个项目挂了我还可以理解，可能写文档的同学，刚入手，哎嘿，不只是几次了，也不是单独antd prccomponents了。我只能想到，你们内部问题了，首先你们阿里的程序员肯定比我们这些厉害吧，你们按文档还能出错，只有两种情况，操作者问题，工具问题。毕竟阿里，操作者问题排除。

**Comment by PeachScript** [comment]
看了下是锁 dumi 版本但项目使用的 dumi 主题包又依赖新版本导致的问题，我们看下有没有合适的方案能让维护者感知到版本不兼容

感谢对 dumi 的认可，以及非常抱歉我们的开源产品给你带来了不好的使用体验
