### ISSUE TITLE
feat: 在 umi 项目中使用 dumi 

### ISSUE THREAD

**Issue by imvkmark** [umijs/dumi#288]
### Question
```
umi : 3.2.16
```

如题 : 
1. 增加 UMI_ENV : .umirc.dumi.ts (dumi官方配置)
2. 运行命令 `UMI_ENV=dumi dumi dev`

出现 : 

```
ENOENT: no such file or directory, open '/Users/duoli/Documents/workbench/l.play/react_pc/user/pages/profile'
Error: ENOENT: no such file or directory, open '/Users/duoli/Documents/workbench/l.play/react_pc/user/pages/profile'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at _default (/Users/duoli/Documents/workbench/l.play/react_pc/node_modules/dumi/node_modules/@umijs/preset-dumi/lib/routes/getFrontMatter.js:49:33)
    at /Users/duoli/Documents/workbench/l.play/react_pc/node_modules/dumi/node_modules/@umijs/preset-dumi/lib/routes/decorator/frontMatter.js:53:91
    at Array.map (<anonymous>)
    at Object.frontmatter (/Users/duoli/Documents/workbench/l.play/react_pc/node_modules/dumi/node_modules/@umijs/preset-dumi/lib/routes/decorator/frontMatter.js:52:17)
    at /Users/duoli/Documents/workbench/l.play/react_pc/node_modules/dumi/node_modules/@umijs/preset-dumi/lib/routes/decorator/index.js:57:68
    at Array.reduce (<anonymous>)
    at RouteDecorator.process (/Users/duoli/Documents/workbench/l.play/react_pc/node_modules/dumi/node_modules/@umijs/preset-dumi/lib/routes/decorator/index.js:57:28)
    at _default (/Users/duoli/Documents/workbench/l.play/react_pc/node_modules/dumi/node_modules/@umijs/preset-dumi/lib/routes/decorator/index.js:73:20)

```
尝试很长时间一直没有办法解决~, 希望能有个 在 umi 项目中使用 dumi 的文档.

**Comment by PeachScript** [comment]
请提供复现 repo

**Comment by imvkmark** [comment]
重新创建了一个项目, 按照自己的了解来进行处理的

repo : https://github.com/imvkmark/umi-demo.git

执行错误 : 
```
ENOENT: no such file or directory, open '/Users/duoli/Documents/workbench/github/demos/umi-demo/@/pages/index'
Error: ENOENT: no such file or directory, open '/Users/duoli/Documents/workbench/github/demos/umi-demo/@/pages/index'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at _default (/Users/duoli/Documents/workbench/github/demos/umi-demo/node_modules/dumi/node_modules/@umijs/preset-dumi/lib/routes/getFrontMatter.js:49:33)
    at /Users/duoli/Documents/workbench/github/demos/umi-demo/node_modules/dumi/node_modules/@umijs/preset-dumi/lib/routes/decorator/frontMatter.js:53:91
    at Array.map (<anonymous>)
    at Object.frontmatter (/Users/duoli/Documents/workbench/github/demos/umi-demo/node_modules/dumi/node_modules/@umijs/preset-dumi/lib/routes/decorator/frontMatter.js:52:17)
    at /Users/duoli/Documents/workbench/github/demos/umi-demo/node_modules/dumi/node_modules/@umijs/preset-dumi/lib/routes/decorator/index.js:57:68
    at Array.reduce (<anonymous>)
    at RouteDecorator.process (/Users/duoli/Documents/workbench/github/demos/umi-demo/node_modules/dumi/node_modules/@umijs/preset-dumi/lib/routes/decorator/index.js:57:28)
    at _default (/Users/duoli/Documents/workbench/github/demos/umi-demo/node_modules/dumi/node_modules/@umijs/preset-dumi/lib/routes/decorator/index.js:73:20)
```

**Comment by xiaohuoni** [comment]
@imvkmark dumi 不支持 routes 配置，启动的时候需要删除。

**Comment by xiaohuoni** [comment]
@PeachScript 应该忽略掉 routes 配置？

**Comment by PeachScript** [comment]
@xiaohuoni routes 是用来提供自定义路由的，能配置 md 为 page component，但没有经过充分测试

**Comment by imvkmark** [comment]
> @xiaohuoni routes 是用来提供自定义路由的，能配置 md 为 page component，但没有经过充分测试

这里能否改变个配置文件, 让两个配置文件分开,如果是 置空 routes, 也不可以, 因为两份配置文件是输入 deepmerge

**Comment by xiaohuoni** [comment]
@imvkmark 嗯，这是一个需求，思考一下，怎么处理比较好。

**Comment by xiaohuoni** [comment]
其实，是因为 dumi 并不是简单的 umi 插件。更贴切的描述是 umi 的关于文档构建的场景化产物。反而更没有考虑和 umi 项目的融合。

**Comment by PeachScript** [comment]
Umi 集成模式已 beta 发布，欢迎试用：https://d.umijs.org/lab#umi-inregrated-mode
