### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by long-zhuge** [umijs/dumi#305]
### Question

使用 build docs 时报错，查询了 p-limit 包的 [issues](https://github.com/sindresorhus/p-limit/issues/33)，说是捆绑打包使用的问题。

- 系统：macOS 10.14.6
- npm：5.6.0
- node: 8.11.4
- dumi: 1.0.34

### Sample Code

```
Unexpected token {
/Users/chenlong/Desktop/我的/td-antd/node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:30
                } catch {}
                        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (/Users/chenlong/Desktop/我的/td-antd/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/Users/chenlong/Desktop/我的/td-antd/node_modules/pirates/lib/index.js:104:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
npm ERR! code ELIFECYCLE

```

**Comment by DongZhe93** [comment]
升级 Nodejs 版本

**Comment by PeachScript** [comment]
无法复现，先确保 Node.js 版本号符合要求吧：
<img width="410" alt="图片" src="https://user-images.githubusercontent.com/5035925/92066934-a62ceb00-edd5-11ea-8497-f9d1f6be5bae.png">
