### ISSUE TITLE
bug: 手动安装 mini-css-extract-plugin，打包报错

### ISSUE THREAD

**Issue by crazyair** [umijs/dumi#478]
```
build failed
Error: build failed
    at compiler.run (/Users/crazyair/Code/yforms/node_modules/@umijs/bundler-webpack/lib/index.js:138:27)
    at finalCallback (/Users/crazyair/Code/yforms/node_modules/@umijs/bundler-webpack/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at runWithDependencies.err (/Users/crazyair/Code/yforms/node_modules/@umijs/bundler-webpack/node_modules/webpack/lib/MultiCompiler.js:277:6)
    at done (/Users/crazyair/Code/yforms/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/Users/crazyair/Code/yforms/node_modules/@umijs/bundler-webpack/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at err (/Users/crazyair/Code/yforms/node_modules/@umijs/bundler-webpack/node_modules/webpack/lib/MultiCompiler.js:188:7)
    at compiler.run (/Users/crazyair/Code/yforms/node_modules/@umijs/bundler-webpack/node_modules/webpack/lib/MultiCompiler.js:270:7)
    at finalCallback (/Users/crazyair/Code/yforms/node_modules/@umijs/bundler-webpack/node_modules/webpack/lib/Compiler.js:257:39)
    at hooks.done.callAsync.err (/Users/crazyair/Code/yforms/node_modules/@umijs/bundler-webpack/node_modules/webpack/lib/Compiler.js:273:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/crazyair/Code/yforms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/crazyair/Code/yforms/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/crazyair/Code/yforms/node_modules/@umijs/bundler-webpack/node_modules/webpack/lib/Compiler.js:271:21)
    at hooks.afterCompile.callAsync.err (/Users/crazyair/Code/yforms/node_modules/@umijs/bundler-webpack/node_modules/webpack/lib/Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/crazyair/Code/yforms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/crazyair/Code/yforms/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/crazyair/Code/yforms/node_modules/@umijs/bundler-webpack/node_modules/webpack/lib/Compiler.js:678:31)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


```

仓库：https://github.com/crazyair/yforms 
```
yarn 
yarn doc:build 
```

### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

**Comment by crazyair** [comment]
@PeachScript

**Comment by PeachScript** [comment]
试了下应该没问题了，推测是 Umi 3.4 做依赖打包解决的：https://github.com/sorrycc/blog/issues/97

issue 关闭
