### ISSUE TITLE
Error: EINVAL: invalid argument, mkdir

### ISSUE THREAD

**Issue by whaty** [umijs/dumi#540]
### Sample Code
$ dumi build
i Compiling Webpack
[Error: EINVAL: invalid argument, mkdir 'C:\idea_project\portal\docs-dist\~demos\:uuid'] {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'mkdir',
  path: 'C:\\idea_project\\portal\\docs-dist\\~demos\\:uuid'
}
build failed
Error: build failed
    at C:\idea_project\portal\node_modules\@umijs\bundler-webpack\lib\index.js:138:27
    at finalCallback (C:\idea_project\portal\node_modules\webpack\lib\MultiCompiler.js:254:12)
    at C:\idea_project\portal\node_modules\webpack\lib\MultiCompiler.js:275:14
    at C:\idea_project\portal\node_modules\neo-async\async.js:2830:7
    at done (C:\idea_project\portal\node_modules\neo-async\async.js:2925:13)
    at C:\idea_project\portal\node_modules\webpack\lib\MultiCompiler.js:186:23
    at C:\idea_project\portal\node_modules\webpack\lib\MultiCompiler.js:267:15
    at finalCallback (C:\idea_project\portal\node_modules\webpack\lib\Compiler.js:257:39)
    at C:\idea_project\portal\node_modules\webpack\lib\Compiler.js:279:21
    at C:\idea_project\portal\node_modules\webpack\lib\Compiler.js:480:22
    at C:\idea_project\portal\node_modules\neo-async\async.js:2830:7
    at done (C:\idea_project\portal\node_modules\neo-async\async.js:3517:9)
    at writeOut (C:\idea_project\portal\node_modules\webpack\lib\Compiler.js:369:23)
    at C:\idea_project\portal\node_modules\mkdirp\index.js:48:53
    at FSReqCallback.oncomplete (fs.js:167:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by PeachScript** [comment]
Duplicate with #473 , closed
