### ISSUE TITLE
bug:  启动时报错

### ISSUE THREAD

**Issue by suedar** [umijs/dumi#642]
### Versions

- dumi:  ^1.1.0
- node: v14.16.0
- npm:  6.14.11
- OS: macos Catalina 10.15.7

### Steps to reproduce
旧项目启动报错

url.includes is not a function
TypeError: url.includes is not a function
    at _default (node_modules/@umijs/preset-dumi/lib/utils/getRepoUrl.js:36:32)
    at Object.<anonymous> (react-pro-components/node_modules/@umijs/preset-dumi/lib/plugins/features/config.js:58:38)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (node_modules/@umijs/preset-dumi/lib/plugins/features/config.js:30:103)
    at _next (node_modules/@umijs/preset-dumi/lib/plugins/features/config.js:32:194)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by suedar** [comment]
我知道了 package.json 的 repository 的 url 不能为空
