### ISSUE TITLE
bug: mhchemParser 依赖报错

### ISSUE THREAD

**Issue by Simon-Bin** [umijs/dumi#657]
### Versions

- dumi:1.0.15
- node:v12.16.1
- npm:6.13.4
- OS:window10
- Browser:chrome

### Steps to reproduce
最新的模板，yarn start
### What is Expected?
正常运行
### What is actually happening?
```
export class mhchemParser {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Module._compile (D:\workspace\xx-ui\node_modules\@umijs\deps\compiled\babel\bundle.js:141004:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.newLoader [as .js] (D:\workspace\xx-ui\node_modules\@umijs\deps\compiled\babel\bundle.js:141009:7)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\workspace\xx-ui\node_modules\mathjax-full\ts\input\tex\mhchem\MhchemConfiguration.ts:32:1)
Done in 3.04s.
```

降级到1.0.14 可以正常运行

**Comment by Simon-Bin** [comment]
yarn依赖问题 写死1.0.15版本号解决了

**Comment by BovineBoy** [comment]
如果lerna依赖的版本在4.0以上，应该是写死版本号1.1.8

**Comment by PeachScript** [comment]
上游依赖问题，dumi 已临时处理，不要写死版本号，详细情况：https://github.com/umijs/dumi/discussions/659
