### ISSUE TITLE
执行npx dumi build，报错。

### ISSUE THREAD

**Issue by fanhualei** [umijs/dumi#666]
# 执行npx dumi build，报错，也没弄明白是啥问题？

昨天新写了一个文档，上传到[gitee上了](https://gitee.com/fanhualei/wukong-mall-learn)，在本地好好的，但是编译就出现错误了，也不知道怎么调试。

```shell
npx dumi build

* Webpack █████████████████████████ emitting (95%)
 OptimizeCssAssetsWebpackPlugin

[Error: EINVAL: invalid argument, mkdir 'E:\00-code\00-wukong-mall\wukong-mall-learn\docs-dist\~demos\:uuid'] {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'mkdir',
  path: 'E:\\00-code\\00-wukong-mall\\wukong-mall-learn\\docs-dist\\~demos\\:uuid'
}
build failed
Error: build failed
    at E:\00-code\00-wukong-mall\wukong-mall-learn\node_modules\@umijs\bundler-webpack\lib\index.js:151:27
    at finalCallback (E:\00-code\00-wukong-mall\wukong-mall-learn\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:108196:12)
    at E:\00-code\00-wukong-mall\wukong-mall-learn\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:108217:14
    at E:\00-code\00-wukong-mall\wukong-mall-learn\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:67111:7
    at done (E:\00-code\00-wukong-mall\wukong-mall-learn\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:67206:13)
    at E:\00-code\00-wukong-mall\wukong-mall-learn\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:108128:23
    at E:\00-code\00-wukong-mall\wukong-mall-learn\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:108209:15
    at finalCallback (E:\00-code\00-wukong-mall\wukong-mall-learn\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:98589:39)
    at E:\00-code\00-wukong-mall\wukong-mall-learn\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:98611:21
    at E:\00-code\00-wukong-mall\wukong-mall-learn\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:98812:22
    at E:\00-code\00-wukong-mall\wukong-mall-learn\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:67111:7
    at done (E:\00-code\00-wukong-mall\wukong-mall-learn\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:67798:9)
    at writeOut (E:\00-code\00-wukong-mall\wukong-mall-learn\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:98701:23)
    at E:\00-code\00-wukong-mall\wukong-mall-learn\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:61973:53
    at FSReqCallback.oncomplete (fs.js:158:21)

```

**Comment by xrkffgg** [comment]
win 环境下 开启 exportStatic 会报错

**Comment by xrkffgg** [comment]
Fixed in https://github.com/umijs/umi/pull/6469 等发布吧

**Comment by fanhualei** [comment]
> win 环境下 开启 exportStatic 会报错

我是不是下载到unbuntu上，进行编译就不会报错了？ 

另外如果在github上，用github pages来进行自动化编译，是不是就不会报错了？

**Comment by xrkffgg** [comment]
可以的

**Comment by fanhualei** [comment]
> 可以的

换成ubuntu，就可以编译好了。我把这个传递到，https://ant-learning.redhtc.com/ ，可以正常显示了。

怎么能用gitee 来编译呢？ 然后发布到giteePages

**Comment by xrkffgg** [comment]
可以参考一下 https://github.com/umijs/umi/issues/5921 获取打包后的文件
