### ISSUE TITLE
bug: 无法在文档中的 `<a>` 内使用 `<img>`

### ISSUE THREAD

**Issue by Yue-plus** [umijs/dumi#778]
### Versions

- dumi: ^1.0.16
- node: 14.15.4
- npm: 6.14.10
- OS: Windows 10
- Browser: Firefox

### Steps to reproduce

初始化一个文档模式的组件库开发脚手架

```bash
yarn create @umijs/dumi-lib
```

将一张图片复制到 `docs/` 目录下

编辑 `docs/index.md` 文件：

```diff
 ## Hello testDumi!

+<a href="/">
+ <img src="./Yue-plus.png" />
+  Home
+</a>
```

开启本地服务器：

```bash
yarn start
```

报错：

![D($F5 23JUAY6V5U7(38U1N](https://user-images.githubusercontent.com/33195150/126085784-81157653-d502-44e6-a7d8-9718c64dec18.png)

### What is Expected?

`<a>` 标签内应该是可以使用 `<img>` 标签的。

### What is actually happening?

报错信息：

```bash
Yue_plus@DESKTOP-T281IIM MINGW64 ~/Desktop/testDumi
$ yarn start
yarn run v1.22.5
$ dumi dev
Starting the development server...

× Webpack
  Compiled with some errors in 9.58s

 ERROR  Failed to compile with 1 errors                                                                                                  上午7:33:16

 error  in ./docs/index.md

Module build failed (from ./node_modules/@umijs/preset-dumi/lib/loader/index.js):
TypeError: values.join is not a function
    at stringify (C:\Users\Yue_plus\Desktop\testDumi\node_modules\space-separated-tokens\index.js:16:17)
    at serializeAttribute (C:\Users\Yue_plus\Desktop\testDumi\node_modules\hast-util-to-html\lib\element.js:155:68)
    at serializeAttributes (C:\Users\Yue_plus\Desktop\testDumi\node_modules\hast-util-to-html\lib\element.js:83:15)
    at Object.serializeElement [as element] (C:\Users\Yue_plus\Desktop\testDumi\node_modules\hast-util-to-html\lib\element.js:31:11)
    at serialize (C:\Users\Yue_plus\Desktop\testDumi\node_modules\hast-util-to-html\lib\one.js:25:29)
    at toHtml (C:\Users\Yue_plus\Desktop\testDumi\node_modules\hast-util-to-html\lib\index.js:29:10)
    at C:\Users\Yue_plus\Desktop\testDumi\node_modules\@umijs\preset-dumi\lib\transformer\remark\link.js:81:87
    at Array.map (<anonymous>)
    at C:\Users\Yue_plus\Desktop\testDumi\node_modules\@umijs\preset-dumi\lib\transformer\remark\link.js:81:48
    at overload (C:\Users\Yue_plus\Desktop\testDumi\node_modules\unist-util-visit\index.js:27:12)

 @ ./src/.umi/core/routes.ts 70:19-78
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

 WAIT  Compiling...                                                                                                                      上午7:33:16


× Webpack
  Compiled with some errors in 482.81ms

 ERROR  Failed to compile with 1 errors                                                                                                  上午7:33:17

 error  in ./docs/index.md

Module build failed (from ./node_modules/@umijs/preset-dumi/lib/loader/index.js):
TypeError: values.join is not a function
    at stringify (C:\Users\Yue_plus\Desktop\testDumi\node_modules\space-separated-tokens\index.js:16:17)
    at serializeAttribute (C:\Users\Yue_plus\Desktop\testDumi\node_modules\hast-util-to-html\lib\element.js:155:68)
    at serializeAttributes (C:\Users\Yue_plus\Desktop\testDumi\node_modules\hast-util-to-html\lib\element.js:83:15)
    at Object.serializeElement [as element] (C:\Users\Yue_plus\Desktop\testDumi\node_modules\hast-util-to-html\lib\element.js:31:11)
    at serialize (C:\Users\Yue_plus\Desktop\testDumi\node_modules\hast-util-to-html\lib\one.js:25:29)
    at toHtml (C:\Users\Yue_plus\Desktop\testDumi\node_modules\hast-util-to-html\lib\index.js:29:10)
    at C:\Users\Yue_plus\Desktop\testDumi\node_modules\@umijs\preset-dumi\lib\transformer\remark\link.js:81:87
    at Array.map (<anonymous>)
    at C:\Users\Yue_plus\Desktop\testDumi\node_modules\@umijs\preset-dumi\lib\transformer\remark\link.js:81:48
    at overload (C:\Users\Yue_plus\Desktop\testDumi\node_modules\unist-util-visit\index.js:27:12)

 @ ./src/.umi/core/routes.ts 70:19-78
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts
```

**Comment by Yue-plus** [comment]
在 `packages/preset-dumi/src/transformer/fixtures/raw/remark-link.md` 添加以下内容：

```diff
+ <a href="https://d.umijs.org/some.md"><img src="" alt="test" /></a>
```

在 `packages/preset-dumi/src/transformer/fixtures/expect/remark-link.html` 做出以下修改：

```diff
- <Link to="https://d.umijs.org/some.md">External Link</Link></p></div>
+ <Link to="https://d.umijs.org/some.md">External Link</Link>
+ <Link to="https://d.umijs.org/some.md"><img src="" alt="test" /></Link></p></div>
```

运行测试：

```bash
umi-test packages/preset-dumi/src/transformer/test/remark-link.test.ts
```

测试未通过：

```bash
 FAIL  packages/preset-dumi/src/transformer/test/remark-link.test.ts (8.796 s)
  link example
    × transform md to jsx (222 ms)

  ● link example › transform md to jsx

    expect(received).toEqual(expected) // deep equality

    Expected: "<div className=\"markdown\"><p><Link to=\"./test\" />
    <Link to=\"./test\" />
    <Link to=\"./test\" />
    <Link to=\"/test\" />
    <Link to=\"./test\" />
    <Link to=\"/test\" />
    <Link to=\"./a/test\" />
    <Link to=\"/a/test\" />
    <Link to=\"./a/test\" />
    <Link to=\"/a/test\" />
    <AnchorLink to=\"./test#header\" />
    <AnchorLink to=\"./a/test#header\" />
    <AnchorLink to=\"./test#header\" />
    <AnchorLink to=\"./a/test#header\" />
    <AnchorLink to=\"/test#header\" />
    <AnchorLink to=\"/a/test#header\" />
    <AnchorLink to=\"/test#header\" />
    <AnchorLink to=\"/a/test#header\" />
    <AnchorLink to=\"/a/test?a=1&b=2#header\" />
    <AnchorLink to=\"/a/test?a=1&b=2#header\" />
    <Link to=\"/test\"><code>test</code></Link>
    <Link to=\"https://d.umijs.org/some.md\">External Link</Link>
    <Link to=\"https://d.umijs.org/some.md\">External Link</Link>
    <Link to=\"https://d.umijs.org/some.md\"><img src=\"\" alt=\"test\" /></Link></p></div>"
    Received: ""

      11 |       .content;
      12 |     // compare transform content
    > 13 |     expect(winEOL(result)).toEqual(
         |                            ^
      14 |       winEOL(
      15 |         fs
      16 |           .readFileSync(path.join(__dirname, '../fixtures/expect/remark-link.html'), 'utf8')

      at Object.<anonymous> (packages/preset-dumi/src/transformer/test/remark-link.test.ts:13:28)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        10.091 s
Ran all test suites matching /packages\\preset-dumi\\src\\transformer\\test\\remark-link.test.ts/i.
AssertionError [ERR_ASSERTION]: Test with jest failed
```

**Comment by Yue-plus** [comment]
在 `docs/index.zh-CN.md` 文件中手动测试：
------

这样写并不报错，且能在页面上显示：

```md
<a href="/">
  <img alt="test" />
</a>
```

一旦给 `<img>` 标签加上 `src=""` 就会报错：

![image](https://user-images.githubusercontent.com/33195150/126422018-06350c7c-947d-40cd-867c-1e1a5362bd59.png)

**Comment by PeachScript** [comment]
@Yue-plus 来个 PR 修复？

**Comment by Yue-plus** [comment]
> @Yue-plus 来个 PR 修复？

然而我还是不知道到底是哪里的问题
![@CBG{8OKH RZJLD2@6PC)MG](https://user-images.githubusercontent.com/33195150/126424516-b9d36bbc-2da0-41d2-a9f1-51a01bec8c0a.png)

**Comment by ltaoo** [comment]
看了下是 `packages/preset-dumi/src/transformer/remark/index.ts` 这里处理 `markdown`，先处理了图片，把属性转成了 `src: 'require(".Yue-plus.png")'`，再通过 `hast-util-to-html` 库转换的时候就有问题，如果把图片的处理放在 `link` 的处理后面就没问题了。

#791 https://github.com/umijs/dumi/pull/791
