### ISSUE TITLE
bug: Error: 'default' is not exported

### ISSUE THREAD

**Issue by sxfmao** [umijs/dumi#785]
### Versions

- dumi:1.1.23
- node:v15.6.0
- npm:
- OS:
- Browser:

### Steps to reproduce

```
$ yarn build
yarn run v1.22.10
$ father-build
Clean dist directory
Build cjs with rollup
'@@/core/umiExports' is imported by node_modules\umi\dist\index.esm.js, but could not be resolved – treating it as an external dependency
×  error     Error: 'default' is not exported by node_modules\history-with-query\node_modules\query-string\index.js, imported by node_modules\history-with-query\esm\history.js
    at error (D:\Project\dumi\node_modules\rollup\dist\shared\rollup.js:5253:30)
    at Module.error (D:\Project\dumi\node_modules\rollup\dist\shared\rollup.js:9821:16)
    at handleMissingExport (D:\Project\dumi\node_modules\rollup\dist\shared\rollup.js:9710:28)
    at Module.traceVariable (D:\Project\dumi\node_modules\rollup\dist\shared\rollup.js:10214:24)
    at ModuleScope.findVariable (D:\Project\dumi\node_modules\rollup\dist\shared\rollup.js:8733:39)
    at FunctionScope.findVariable (D:\Project\dumi\node_modules\rollup\dist\shared\rollup.js:2782:38)
    at ChildScope.findVariable (D:\Project\dumi\node_modules\rollup\dist\shared\rollup.js:2782:38)
    at TrackingScope.findVariable (D:\Project\dumi\node_modules\rollup\dist\shared\rollup.js:2782:38)
    at BlockScope.findVariable (D:\Project\dumi\node_modules\rollup\dist\shared\rollup.js:2782:38)
    at MemberExpression.bind (D:\Project\dumi\node_modules\rollup\dist\shared\rollup.js:6437:49)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What is Expected?

解决报错

### What is actually happening?

我添加query-string包，又会报其他包的这种错误

**Comment by PeachScript** [comment]
用到的依赖写进 dependencies

**Comment by sxfmao** [comment]
> 依赖的依赖写进依赖

为什么官方的demo不需要引入
我的只是多引入了下面几个包并基于这几个包写了几个组件
```
"@ant-design/icons": "^4.6.2",
    "@ant-design/pro-card": "^1.14.7",
    "@ant-design/pro-form": "^1.32.1",
    "@ant-design/pro-layout": "^6.22.1",
    "@ant-design/pro-table": "^2.43.6",
    "antd": "^4.16.8",
```
umi项目基于这几个包写的组件 也没有报错啊 也没有引入报错的包

**Comment by PeachScript** [comment]
@sxfmao 你看到的评论内容不对，关闭 Chrome 浏览器自动翻译再看

**Comment by sxfmao** [comment]
> @sxfmao 你看到的评论内容不对，关闭 Chrome 浏览器自动翻译再看

我知道你评论的内容。

#### 我的产生的问题是：
我加了query-string包后，又会有其他的包报这样的错误，我一直加，导致加了好多包。
#### 疑惑
这几个包我并没有用到，我查了一下是dumi用到的，为什么我用官方模板，不修改，打包是正常的，我加了个组件，打包就报这样的错误，而且我的组件是基于下面几个包的，并没有用的其他的包
```
"@ant-design/icons": "^4.6.2",
"@ant-design/pro-card": "^1.14.7",
"@ant-design/pro-form": "^1.32.1",
"@ant-design/pro-layout": "^6.22.1",
"@ant-design/pro-table": "^2.43.6",
"antd": "^4.16.8",
```
