### ISSUE TITLE
bug: babel 模式构建报错

### ISSUE THREAD

**Issue by SinHide** [umijs/dumi#991]
### Versions

- dumi: 1.1.36
- node: 14.15.0
- yarn: 1.22.4

### Steps to reproduce

执行 `yarn build` 构建

```bash
TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: TypeScript: Compilation failed
    at Output.mightFinish (/Users/WorkSpace/duim/node_modules/gulp-typescript/release/output.js:130:43)
    at /Users/WorkSpace/duim/node_modules/gulp-typescript/release/output.js:65:22
Emitted 'error' event on Duplexify instance at:
    at Duplexify._destroy (/Users/WorkSpace/duim/node_modules/duplexify/index.js:191:15)
    at /Users/WorkSpace/duim/node_modules/duplexify/index.js:182:10
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error Command failed with exit code 1.
```

### What is Expected?
正常构建

issue 里的办法都试过了，还是报错。

[#48 (comment)](https://github.com/umijs/father/issues/48#issuecomment-730857244)
[#227 (comment)](https://github.com/umijs/father/issues/227#issuecomment-720928000)
这两个都不行。

**Comment by SinHide** [comment]
锁 React 16 版本的也不行。
